# Generated by Django 3.0.8 on 2020-08-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_ID', models.TextField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('AvS', models.IntegerField()),
                ('BkS', models.IntegerField()),
                ('DateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('username', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
