# Generated by Django 3.0.8 on 2020-08-19 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 19, 7, 31, 897253)),
        ),
        migrations.AddField(
            model_name='bus',
            name='Rate',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 19, 19, 7, 31, 897253)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
