# Generated by Django 3.0.8 on 2020-08-19 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200819_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='AvS',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='bus',
            name='BkS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 21, 29, 30, 684547)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 19, 21, 29, 30, 684547)),
        ),
    ]
