# Generated by Django 3.0.8 on 2020-08-19 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200819_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 21, 42, 49, 417855)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 19, 21, 42, 49, 418855)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_ID',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
