# Generated by Django 3.0.8 on 2020-08-20 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200819_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 20, 22, 0, 6, 130736)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 20, 22, 0, 6, 130736)),
        ),
    ]
