# Generated by Django 3.0.8 on 2020-08-20 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20200820_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 20, 22, 28, 2, 681958)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 20, 22, 28, 2, 681958)),
        ),
    ]
