# Generated by Django 3.0.8 on 2020-08-20 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20200820_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 20, 22, 30, 38, 182429)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 20, 22, 30, 38, 182428)),
        ),
    ]
