# Generated by Django 3.0.8 on 2020-08-21 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20200821_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.date(2020, 8, 21)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 21, 8, 39, 7, 933574, tzinfo=utc)),
        ),
    ]
