# Generated by Django 3.0.8 on 2020-08-21 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20200821_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 21, 8, 40, 27, 450678, tzinfo=utc)),
        ),
    ]
