# Generated by Django 3.0.8 on 2020-08-21 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20200821_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 21, 8, 41, 16, 909371, tzinfo=utc)),
        ),
    ]
