# Generated by Django 3.0.8 on 2020-08-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20200821_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='Time',
            new_name='BTime',
        ),
        migrations.AddField(
            model_name='bus',
            name='BoardPoint',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='DTime',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='bus',
            name='DropPoint',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='agency',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='bustype',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='From',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='To',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
