# Generated by Django 3.0.8 on 2020-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20200821_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='BoardPoint',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
