# Generated by Django 3.0.8 on 2020-08-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20200821_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='BTime',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='bus',
            name='BoardPoint',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='DTime',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='bus',
            name='DropPoint',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bus',
            name='From',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='To',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='agency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_ID',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bustype',
            field=models.CharField(default='', max_length=20),
        ),
    ]
