# Generated by Django 3.0.8 on 2020-08-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_auto_20200821_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='Date',
        ),
    ]
