# Generated by Django 3.0.8 on 2020-08-28 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_bus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 13, 10, 36, 483714)),
        ),
    ]
