# Generated by Django 3.0.8 on 2020-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_auto_20200828_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default='2020-08-29', null=True),
        ),
    ]
