# Generated by Django 3.0.8 on 2020-08-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20200828_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='Date',
        ),
    ]
