# Generated by Django 3.0.8 on 2020-08-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_remove_bus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=''),
        ),
    ]
