# Generated by Django 3.0.8 on 2020-08-28 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_bus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 15, 46, 9, 98711)),
        ),
    ]
