# Generated by Django 3.0.8 on 2020-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_auto_20200828_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Date',
            field=models.DateField(default=''),
        ),
    ]
