# Generated by Django 3.0.8 on 2020-09-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_auto_20200828_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='TravelTime',
            field=models.CharField(default='', max_length=10),
        ),
    ]
