# Generated by Django 3.0.8 on 2020-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_bus_traveltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Bus_ID', models.CharField(default='', max_length=20)),
                ('Departure_Date', models.CharField(default='', max_length=20)),
                ('JTime', models.CharField(default='', max_length=20)),
                ('Pickup', models.CharField(default='', max_length=50)),
                ('Destination', models.CharField(default='', max_length=50)),
                ('seniors', models.IntegerField()),
                ('ladies', models.IntegerField()),
                ('PwD', models.IntegerField()),
                ('transgender', models.IntegerField()),
                ('general', models.IntegerField()),
                ('charges', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Message', models.TextField(max_length=200)),
            ],
        ),
    ]
